remote_ue_testers:
  hosts:
    remotetester.site-a:
      ansible_host: 10.0.1.4
      ansible_user: nick
      ansible_connection: ssh
      ansible_ssh_pass: password
      become_user: root 
      ansible_become_password: password
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'